
# set run_base_instance = false if you want create multiple instances 
default["tomee"]["run_base_instance"] = true
default["tomee"]["name"]="tomee"
default["tomee"]["user"]="tmuser"
default["tomee"]["group"]="tomee"

default["tomee"]["tomee_url"] = "http://mirror.nohup.it/apache/tomee/tomee-1.7.1/apache-tomee-1.7.1-plume.tar.gz"

default["tomee"]["port"] = 8080
default["tomee"]["proxy_port"] = nil
default["tomee"]["ssl_port"] = 8443
default["tomee"]["ssl_proxy_port"] = nil
default["tomee"]["ajp_port"] = 8009
default["tomee"]["shutdown_port"] = 8005

default["tomee"]["catalina_options"] = ""
default["tomee"]["java_options"] = "-Xmx128M -Djava.awt.headless=true"
default["tomee"]["use_security_manager"] = false
default["tomee"]["authbind"] = "no"
default["tomee"]["deploy_manager_apps"] = true
#default["tomee"]["max_threads"] = nil
#default["tomee"]["ssl_max_threads"] = 150
default["tomee"]["ssl_cert_file"] = nil
default["tomee"]["ssl_key_file"] = nil
default["tomee"]["ssl_chain_files"] = []
default["tomee"]["keystore_file"] = "keystore.jks"
default["tomee"]["keystore_type"] = "jks"
# The keystore and truststore passwords will be generated by the
# openssl cookbook's secure_password method in the recipe if they are
# not otherwise set. Do not hardcode passwords in the cookbook.
default["tomee"]["keystore_password"] = "secret"
default["tomee"]["truststore_password"] = nil
default["tomee"]["truststore_file"] = "#{node["java"]["java_home"]}/jre/lib/security/cacerts"
default["tomee"]["truststore_type"] = "pem"
default["tomee"]["certificate_dn"] = "cn=localhost"
default["tomee"]["loglevel"] = "INFO"
default["tomee"]["tomcat_auth"] = "true"
default["tomee"]["instances"] = {}

default["tomee"]["home"] = "/opt/#{node["tomee"]["name"]}"
default["tomee"]["base"] = "/opt/#{node["tomee"]["name"]}"
default["tomee"]["config_dir"] = "#{node["tomee"]["base"]}/conf"
default["tomee"]["log_dir"] = "#{node["tomee"]["base"]}/logs"
default["tomee"]["tmp_dir"] = "#{node["tomee"]["base"]}/temp"
default["tomee"]["work_dir"] = "#{node["tomee"]["base"]}/work"
default["tomee"]["context_dir"] = "#{node["tomee"]["config_dir"]}/Catalina/localhost"
default["tomee"]["webapp_dir"] = "#{node["tomee"]["base"]}/webapps"
default["tomee"]["keytool"] = "keytool"
default["tomee"]["lib_dir"] = "#{node["tomee"]["home"]}/lib"
default["tomee"]["endorsed_dir"] = "#{node["tomee"]["lib_dir"]}/endorsed"
default["tomee"]["catalina_pid"] = "#{node["tomee"]["log_dir"]}/catalina-daemon.pid"
